import {
  createAgentChatPlugin,
  loadActionsFromStaticRegistry,
} from "@agent-native/core/server";
import { getOrgContext } from "@agent-native/core/org";
import { registerEvent } from "@agent-native/core/event-bus";
import { z } from "zod";
// Static-import registry generated by @agent-native/core's Vite plugin at
// build time. Using a static import ensures bundlers (Nitro on Netlify,
// Vercel, AWS-Lambda) include every action module in the server bundle —
// a runtime filesystem scan finds nothing in a bundled function, which is
// why `autoDiscoverActions` on its own produces 404s for action routes in
// production.
import actionsRegistry from "../../.generated/actions-registry.js";

// ---------------------------------------------------------------------------
// Register calendar event-bus events
// ---------------------------------------------------------------------------
registerEvent({
  name: "calendar.event.created",
  description: "A new calendar event was created.",
  payloadSchema: z.object({
    eventId: z.string(),
    title: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    attendees: z.array(z.any()),
    createdBy: z.string(),
  }),
});

registerEvent({
  name: "calendar.event.updated",
  description: "An existing calendar event was updated.",
  payloadSchema: z.object({
    eventId: z.string(),
    title: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    attendees: z.array(z.any()),
    updatedBy: z.string(),
  }),
});

registerEvent({
  name: "calendar.booking.created",
  description: "Someone booked a meeting via a scheduling / booking link.",
  payloadSchema: z.object({
    bookingId: z.string(),
    schedulingLinkSlug: z.string(),
    attendeeName: z.string(),
    attendeeEmail: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    eventTitle: z.string(),
  }),
});

export default createAgentChatPlugin({
  appId: "calendar",
  resolveOrgId: async (event) => {
    const ctx = await getOrgContext(event);
    return ctx.orgId;
  },
  actions: loadActionsFromStaticRegistry(actionsRegistry),
  systemPrompt: `You are an AI calendar assistant. You manage the user's Google Calendar events, bookings, and availability.

## CRITICAL: Use Scripts, Not Raw SQL

Google Calendar events are NOT stored in the local database. They are fetched live from Google Calendar API via scripts. You MUST use the following scripts — never use db-query or db-exec for calendar operations:

- \`pnpm action view-screen\` — See what the user is looking at (current view, date, events). ALWAYS run this first.
- \`pnpm action list-events --from YYYY-MM-DD --to YYYY-MM-DD\` — List events from Google Calendar. The --to date is exclusive, so use tomorrow for today's events.
- \`pnpm action search-events --query "term"\` — Search events by title, people, organizer, location, or description across a broad one-year past/future window. Use this for recurring meetings and "how often do I meet with X?" questions.
- \`pnpm action create-event --title "..." --start "ISO" --end "ISO"\` — Create a new event. Use \`--eventType outOfOffice\` for OOO, \`--eventType focusTime\` for focus time, \`--eventType workingLocation\` for working location, \`--transparency transparent\` to show as Free, \`--visibility private\` for private events, \`--startTimeZone America/Los_Angeles\` for timezone anchoring, \`--colorId 9\` for Google event color, \`--reminders '[{"method":"popup","minutes":10}]'\` for alerts, and \`--attachments '[{"fileUrl":"https://...","title":"Agenda"}]'\` for Drive/HTTPS file links.
- \`pnpm action update-event --id "google-..." --transparency opaque|transparent --visibility default|public|private --reminderMinutes 10 --scope single|all\` — Update event availability, visibility, reminders, timezone, color, attachments, recurrence, or generated video links. Use \`--scope all\` to update an entire recurring series from one occurrence.
- \`pnpm action navigate --view=calendar --calendarViewMode=day\` — Navigate the UI (day/week/month views, dates)
- \`pnpm action navigate --view=calendar --date=YYYY-MM-DD\` — Navigate to a specific date
- \`pnpm action navigate --view=availability\` — Show availability settings
- \`pnpm action navigate --view=booking-links\` — Show booking links
- \`pnpm action update-calendar-visual-preferences --colorMode multi\` — Color the local app UI by meeting type without modifying Google Calendar events
- \`pnpm action update-calendar-visual-preferences --colorMode single --singleColor '#5B9BD5'\` — Use one local display color for the user's Google events
- \`pnpm action check-availability --date YYYY-MM-DD --duration 60\` — Check free slots
- \`pnpm action list-booking-links\` — List existing booking links
- \`pnpm action create-booking-link --title "Meeting" --slug meeting --duration 30\` — Create a booking link
- \`pnpm action duplicate-booking-link --sourceSlug meeting --copies '[...]'\` — Duplicate one booking link into one or more variants

## Local UI Visual Preferences vs Google Calendar Event Color
Use \`create-event\` or \`update-event --colorId 1..11\` when the user wants one specific Google Calendar event color changed. Use \`update-calendar-visual-preferences\` when the user wants broad app-layer display rules such as color-coding meetings by internal/external, 1:1/group, focus time, or one display color for all Google events.

## Google Connection Check
Before answering schedule questions, run view-screen first for context, then use list-events for the requested date range even if the user is currently on Settings, Booking Links, or another non-calendar page. Do not infer a Google Calendar connection problem just because the current page is Settings. Only ask the user to reconnect Google if list-events or the explicit Google status reports an auth/connection error.

For relationship-frequency questions such as "how often do I meet with Mattel?", use search-events with the person's or company's name so recurring series outside the current visible range are included. Do not conclude there are no recurring meetings from a narrow date window alone.

## Context Awareness
The UI writes navigation state including the current view, date, view mode (day/week/month), and selected event ID. Always check view-screen to know what the user sees before responding.

When the user says "show me", "go to", "open", or "switch to" a view or date, ALWAYS use the \`navigate\` action to update the UI first, then fetch/display data. The user expects to SEE the result in the app.`,
  mentionProviders: async () => {
    const { getDb } = await import("../db/index.js");
    const { bookings, bookingLinks, bookingLinkShares } =
      await import("../db/schema.js");
    const { like, desc, and, inArray } = await import("drizzle-orm");
    const { accessFilter } = await import("@agent-native/core/sharing");
    return {
      bookings: {
        label: "Bookings",
        icon: "email",
        search: async (query: string) => {
          const db = getDb();
          // bookings has no ownerEmail — scope via booking-links the caller can access
          const ownedLinks = await db
            .select({ slug: bookingLinks.slug })
            .from(bookingLinks)
            .where(accessFilter(bookingLinks, bookingLinkShares));
          const slugs = ownedLinks.map((l) => l.slug);
          if (slugs.length === 0) return [];
          const scopeClause = inArray(bookings.slug, slugs);
          const rows = query
            ? await db
                .select()
                .from(bookings)
                .where(and(scopeClause, like(bookings.name, `%${query}%`)))
                .limit(15)
            : await db
                .select()
                .from(bookings)
                .where(scopeClause)
                .orderBy(desc(bookings.start))
                .limit(15);
          return rows.map((booking) => ({
            id: booking.id,
            label: `${booking.eventTitle || "Booking"} — ${booking.name}`,
            description: booking.start,
            icon: "document" as const,
            refType: "booking",
            refId: booking.id,
          }));
        },
      },
      "booking-links": {
        label: "Booking Links",
        icon: "document",
        search: async (query: string) => {
          const db = getDb();
          const access = accessFilter(bookingLinks, bookingLinkShares);
          const rows = query
            ? await db
                .select()
                .from(bookingLinks)
                .where(and(access, like(bookingLinks.title, `%${query}%`)))
                .limit(15)
            : await db
                .select()
                .from(bookingLinks)
                .where(access)
                .orderBy(desc(bookingLinks.updatedAt))
                .limit(15);
          return rows.map((link) => ({
            id: link.id,
            label: link.title,
            description: `${link.duration}min · /${link.slug}`,
            icon: "document" as const,
            refType: "booking-link",
            refId: link.id,
          }));
        },
      },
    };
  },
});
